# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mian.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_meter_reading(object):
    def setupUi(self, New_meter_reading):
        New_meter_reading.setObjectName("New_meter_reading")
        New_meter_reading.resize(1920, 1000)
        self.centralwidget = QtWidgets.QWidget(New_meter_reading)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 601, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(360, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color:#86a9f9")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("color:#86a9f9")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(320, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 30, 201, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_125 = QtWidgets.QLabel(self.groupBox_2)
        self.label_125.setGeometry(QtCore.QRect(30, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_125.setFont(font)
        self.label_125.setStyleSheet("color:#3D9140")
        self.label_125.setObjectName("label_125")
        self.label_126 = QtWidgets.QLabel(self.groupBox_2)
        self.label_126.setGeometry(QtCore.QRect(30, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_126.setFont(font)
        self.label_126.setStyleSheet("color:#ff2121")
        self.label_126.setObjectName("label_126")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 160, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.listView = QtWidgets.QListView(self.groupBox_3)
        self.listView.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView.setObjectName("listView")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_1_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_1_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_1_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_1_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_1_5.setObjectName("lineEdit_1_5")
        self.lineEdit_1_6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_1_6.setObjectName("lineEdit_1_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_1_7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_1_7.setObjectName("lineEdit_1_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_1_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_1_8.setText("")
        self.lineEdit_1_8.setObjectName("lineEdit_1_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_1_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_1_9.setText("")
        self.lineEdit_1_9.setObjectName("lineEdit_1_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_12.setObjectName("label_12")
        self.lineEdit_1_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_1_10.setFont(font)
        self.lineEdit_1_10.setText("")
        self.lineEdit_1_10.setObjectName("lineEdit_1_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_13.setObjectName("label_13")
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_1_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_1_1.setText("")
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_14.setObjectName("label_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 160, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.listView_2 = QtWidgets.QListView(self.groupBox_4)
        self.listView_2.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_2.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_2.setObjectName("listView_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_15.setObjectName("label_15")
        self.lineEdit_2_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_2_2.setObjectName("lineEdit_2_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_2_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_2_3.setObjectName("lineEdit_2_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_17.setObjectName("label_17")
        self.lineEdit_2_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_2_4.setObjectName("lineEdit_2_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit_2_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_2_5.setObjectName("lineEdit_2_5")
        self.lineEdit_2_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_2_6.setObjectName("lineEdit_2_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_19.setObjectName("label_19")
        self.lineEdit_2_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_2_7.setObjectName("lineEdit_2_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_20.setObjectName("label_20")
        self.lineEdit_2_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_2_8.setText("")
        self.lineEdit_2_8.setObjectName("lineEdit_2_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_2_9 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_2_9.setText("")
        self.lineEdit_2_9.setObjectName("lineEdit_2_9")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_22.setObjectName("label_22")
        self.lineEdit_2_10 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2_10.setFont(font)
        self.lineEdit_2_10.setStyleSheet("color:#3D9140")
        self.lineEdit_2_10.setText("")
        self.lineEdit_2_10.setObjectName("lineEdit_2_10")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_23.setObjectName("label_23")
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_2_1.setText("")
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_24.setObjectName("label_24")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(970, 160, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.listView_3 = QtWidgets.QListView(self.groupBox_5)
        self.listView_3.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_3.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_3.setObjectName("listView_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_25.setObjectName("label_25")
        self.lineEdit_3_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_26.setObjectName("label_26")
        self.lineEdit_3_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_3_3.setObjectName("lineEdit_3_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_3_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_3_4.setObjectName("lineEdit_3_4")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_28.setObjectName("label_28")
        self.lineEdit_3_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_3_5.setObjectName("lineEdit_3_5")
        self.lineEdit_3_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_3_6.setObjectName("lineEdit_3_6")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_29.setObjectName("label_29")
        self.lineEdit_3_7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_3_7.setObjectName("lineEdit_3_7")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_30.setObjectName("label_30")
        self.lineEdit_3_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_3_8.setText("")
        self.lineEdit_3_8.setObjectName("lineEdit_3_8")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_31.setObjectName("label_31")
        self.lineEdit_3_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_3_9.setText("")
        self.lineEdit_3_9.setObjectName("lineEdit_3_9")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_32.setObjectName("label_32")
        self.lineEdit_3_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3_10.setFont(font)
        self.lineEdit_3_10.setStyleSheet("")
        self.lineEdit_3_10.setText("")
        self.lineEdit_3_10.setObjectName("lineEdit_3_10")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_33.setObjectName("label_33")
        self.lineEdit_3_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_3_1.setText("")
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_34.setObjectName("label_34")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(1430, 160, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.listView_4 = QtWidgets.QListView(self.groupBox_6)
        self.listView_4.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_4.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_4.setObjectName("listView_4")
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_35.setObjectName("label_35")
        self.lineEdit_4_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_4_2.setObjectName("lineEdit_4_2")
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_36.setObjectName("label_36")
        self.lineEdit_4_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_4_3.setObjectName("lineEdit_4_3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_37.setObjectName("label_37")
        self.lineEdit_4_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_4_4.setObjectName("lineEdit_4_4")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_38.setObjectName("label_38")
        self.lineEdit_4_5 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_4_5.setObjectName("lineEdit_4_5")
        self.lineEdit_4_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_4_6.setObjectName("lineEdit_4_6")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_39.setObjectName("label_39")
        self.lineEdit_4_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_4_7.setObjectName("lineEdit_4_7")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_40.setObjectName("label_40")
        self.lineEdit_4_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_4_8.setText("")
        self.lineEdit_4_8.setObjectName("lineEdit_4_8")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_41.setObjectName("label_41")
        self.lineEdit_4_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_4_9.setText("")
        self.lineEdit_4_9.setObjectName("lineEdit_4_9")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_42.setObjectName("label_42")
        self.lineEdit_4_10 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_4_10.setFont(font)
        self.lineEdit_4_10.setStyleSheet("")
        self.lineEdit_4_10.setText("")
        self.lineEdit_4_10.setObjectName("lineEdit_4_10")
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_43.setObjectName("label_43")
        self.lineEdit_4_1 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_4_1.setText("")
        self.lineEdit_4_1.setObjectName("lineEdit_4_1")
        self.label_44 = QtWidgets.QLabel(self.groupBox_6)
        self.label_44.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_44.setObjectName("label_44")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(50, 570, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.listView_12 = QtWidgets.QListView(self.groupBox_10)
        self.listView_12.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_12.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_12.setObjectName("listView_12")
        self.label_115 = QtWidgets.QLabel(self.groupBox_10)
        self.label_115.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_115.setObjectName("label_115")
        self.lineEdit_5_2 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_5_2.setObjectName("lineEdit_5_2")
        self.label_116 = QtWidgets.QLabel(self.groupBox_10)
        self.label_116.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_116.setObjectName("label_116")
        self.lineEdit_5_3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_5_3.setObjectName("lineEdit_5_3")
        self.label_117 = QtWidgets.QLabel(self.groupBox_10)
        self.label_117.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_117.setObjectName("label_117")
        self.lineEdit_5_4 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_5_4.setObjectName("lineEdit_5_4")
        self.label_118 = QtWidgets.QLabel(self.groupBox_10)
        self.label_118.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_118.setObjectName("label_118")
        self.lineEdit_5_5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_5_5.setObjectName("lineEdit_5_5")
        self.lineEdit_5_6 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_5_6.setObjectName("lineEdit_5_6")
        self.label_119 = QtWidgets.QLabel(self.groupBox_10)
        self.label_119.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_119.setObjectName("label_119")
        self.lineEdit_5_7 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_5_7.setObjectName("lineEdit_5_7")
        self.label_120 = QtWidgets.QLabel(self.groupBox_10)
        self.label_120.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_120.setObjectName("label_120")
        self.lineEdit_5_8 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_5_8.setText("")
        self.lineEdit_5_8.setObjectName("lineEdit_5_8")
        self.label_121 = QtWidgets.QLabel(self.groupBox_10)
        self.label_121.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_121.setObjectName("label_121")
        self.lineEdit_5_9 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_5_9.setText("")
        self.lineEdit_5_9.setObjectName("lineEdit_5_9")
        self.label_122 = QtWidgets.QLabel(self.groupBox_10)
        self.label_122.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_122.setObjectName("label_122")
        self.lineEdit_5_10 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_5_10.setFont(font)
        self.lineEdit_5_10.setText("")
        self.lineEdit_5_10.setObjectName("lineEdit_5_10")
        self.label_123 = QtWidgets.QLabel(self.groupBox_10)
        self.label_123.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_123.setObjectName("label_123")
        self.lineEdit_5_1 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_5_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_5_1.setText("")
        self.lineEdit_5_1.setObjectName("lineEdit_5_1")
        self.label_124 = QtWidgets.QLabel(self.groupBox_10)
        self.label_124.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_124.setObjectName("label_124")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(1430, 570, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.listView_9 = QtWidgets.QListView(self.groupBox_7)
        self.listView_9.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_9.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_9.setObjectName("listView_9")
        self.label_85 = QtWidgets.QLabel(self.groupBox_7)
        self.label_85.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_85.setObjectName("label_85")
        self.lineEdit_8_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_8_2.setObjectName("lineEdit_8_2")
        self.label_86 = QtWidgets.QLabel(self.groupBox_7)
        self.label_86.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_86.setObjectName("label_86")
        self.lineEdit_8_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_8_3.setObjectName("lineEdit_8_3")
        self.label_87 = QtWidgets.QLabel(self.groupBox_7)
        self.label_87.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_87.setObjectName("label_87")
        self.lineEdit_8_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_8_4.setObjectName("lineEdit_8_4")
        self.label_88 = QtWidgets.QLabel(self.groupBox_7)
        self.label_88.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_88.setObjectName("label_88")
        self.lineEdit_8_5 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_8_5.setObjectName("lineEdit_8_5")
        self.lineEdit_8_6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_8_6.setObjectName("lineEdit_8_6")
        self.label_89 = QtWidgets.QLabel(self.groupBox_7)
        self.label_89.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_89.setObjectName("label_89")
        self.lineEdit_8_7 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_8_7.setObjectName("lineEdit_8_7")
        self.label_90 = QtWidgets.QLabel(self.groupBox_7)
        self.label_90.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_90.setObjectName("label_90")
        self.lineEdit_8_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_8_8.setText("")
        self.lineEdit_8_8.setObjectName("lineEdit_8_8")
        self.label_91 = QtWidgets.QLabel(self.groupBox_7)
        self.label_91.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_91.setObjectName("label_91")
        self.lineEdit_8_9 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_8_9.setText("")
        self.lineEdit_8_9.setObjectName("lineEdit_8_9")
        self.label_92 = QtWidgets.QLabel(self.groupBox_7)
        self.label_92.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_92.setObjectName("label_92")
        self.lineEdit_8_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_8_10.setFont(font)
        self.lineEdit_8_10.setText("")
        self.lineEdit_8_10.setObjectName("lineEdit_8_10")
        self.label_93 = QtWidgets.QLabel(self.groupBox_7)
        self.label_93.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_93.setObjectName("label_93")
        self.lineEdit_8_1 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_8_1.setText("")
        self.lineEdit_8_1.setObjectName("lineEdit_8_1")
        self.label_94 = QtWidgets.QLabel(self.groupBox_7)
        self.label_94.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_94.setObjectName("label_94")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(510, 570, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.listView_10 = QtWidgets.QListView(self.groupBox_8)
        self.listView_10.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_10.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_10.setObjectName("listView_10")
        self.label_95 = QtWidgets.QLabel(self.groupBox_8)
        self.label_95.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_95.setObjectName("label_95")
        self.lineEdit_6_2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_6_2.setObjectName("lineEdit_6_2")
        self.label_96 = QtWidgets.QLabel(self.groupBox_8)
        self.label_96.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_96.setObjectName("label_96")
        self.lineEdit_6_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_6_3.setObjectName("lineEdit_6_3")
        self.label_97 = QtWidgets.QLabel(self.groupBox_8)
        self.label_97.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_97.setObjectName("label_97")
        self.lineEdit_6_4 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_6_4.setObjectName("lineEdit_6_4")
        self.label_98 = QtWidgets.QLabel(self.groupBox_8)
        self.label_98.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_98.setObjectName("label_98")
        self.lineEdit_6_5 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_6_5.setObjectName("lineEdit_6_5")
        self.lineEdit_6_6 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_6_6.setObjectName("lineEdit_6_6")
        self.label_99 = QtWidgets.QLabel(self.groupBox_8)
        self.label_99.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_99.setObjectName("label_99")
        self.lineEdit_6_7 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_6_7.setObjectName("lineEdit_6_7")
        self.label_100 = QtWidgets.QLabel(self.groupBox_8)
        self.label_100.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_100.setObjectName("label_100")
        self.lineEdit_6_8 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_6_8.setText("")
        self.lineEdit_6_8.setObjectName("lineEdit_6_8")
        self.label_101 = QtWidgets.QLabel(self.groupBox_8)
        self.label_101.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_101.setObjectName("label_101")
        self.lineEdit_6_9 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_6_9.setText("")
        self.lineEdit_6_9.setObjectName("lineEdit_6_9")
        self.label_102 = QtWidgets.QLabel(self.groupBox_8)
        self.label_102.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_102.setObjectName("label_102")
        self.lineEdit_6_10 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_6_10.setFont(font)
        self.lineEdit_6_10.setText("")
        self.lineEdit_6_10.setObjectName("lineEdit_6_10")
        self.label_103 = QtWidgets.QLabel(self.groupBox_8)
        self.label_103.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_103.setObjectName("label_103")
        self.lineEdit_6_1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_6_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_6_1.setText("")
        self.lineEdit_6_1.setObjectName("lineEdit_6_1")
        self.label_104 = QtWidgets.QLabel(self.groupBox_8)
        self.label_104.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_104.setObjectName("label_104")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(970, 570, 430, 391))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.listView_11 = QtWidgets.QListView(self.groupBox_9)
        self.listView_11.setGeometry(QtCore.QRect(0, 70, 431, 261))
        self.listView_11.setStyleSheet("background-color:#c2ccd0;border:none")
        self.listView_11.setObjectName("listView_11")
        self.label_105 = QtWidgets.QLabel(self.groupBox_9)
        self.label_105.setGeometry(QtCore.QRect(20, 80, 72, 31))
        self.label_105.setObjectName("label_105")
        self.lineEdit_7_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_2.setGeometry(QtCore.QRect(100, 80, 101, 31))
        self.lineEdit_7_2.setObjectName("lineEdit_7_2")
        self.label_106 = QtWidgets.QLabel(self.groupBox_9)
        self.label_106.setGeometry(QtCore.QRect(210, 240, 60, 31))
        self.label_106.setObjectName("label_106")
        self.lineEdit_7_3 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_3.setGeometry(QtCore.QRect(290, 80, 121, 31))
        self.lineEdit_7_3.setObjectName("lineEdit_7_3")
        self.label_107 = QtWidgets.QLabel(self.groupBox_9)
        self.label_107.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.label_107.setObjectName("label_107")
        self.lineEdit_7_4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_4.setGeometry(QtCore.QRect(100, 120, 311, 31))
        self.lineEdit_7_4.setObjectName("lineEdit_7_4")
        self.label_108 = QtWidgets.QLabel(self.groupBox_9)
        self.label_108.setGeometry(QtCore.QRect(20, 120, 60, 31))
        self.label_108.setObjectName("label_108")
        self.lineEdit_7_5 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_5.setGeometry(QtCore.QRect(100, 160, 311, 31))
        self.lineEdit_7_5.setObjectName("lineEdit_7_5")
        self.lineEdit_7_6 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_6.setGeometry(QtCore.QRect(100, 200, 311, 31))
        self.lineEdit_7_6.setObjectName("lineEdit_7_6")
        self.label_109 = QtWidgets.QLabel(self.groupBox_9)
        self.label_109.setGeometry(QtCore.QRect(20, 160, 60, 31))
        self.label_109.setObjectName("label_109")
        self.lineEdit_7_7 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_7.setGeometry(QtCore.QRect(100, 240, 101, 31))
        self.lineEdit_7_7.setObjectName("lineEdit_7_7")
        self.label_110 = QtWidgets.QLabel(self.groupBox_9)
        self.label_110.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_110.setObjectName("label_110")
        self.lineEdit_7_8 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_8.setGeometry(QtCore.QRect(280, 240, 131, 31))
        self.lineEdit_7_8.setText("")
        self.lineEdit_7_8.setObjectName("lineEdit_7_8")
        self.label_111 = QtWidgets.QLabel(self.groupBox_9)
        self.label_111.setGeometry(QtCore.QRect(20, 200, 89, 31))
        self.label_111.setObjectName("label_111")
        self.lineEdit_7_9 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_9.setGeometry(QtCore.QRect(100, 280, 311, 31))
        self.lineEdit_7_9.setText("")
        self.lineEdit_7_9.setObjectName("lineEdit_7_9")
        self.label_112 = QtWidgets.QLabel(self.groupBox_9)
        self.label_112.setGeometry(QtCore.QRect(20, 280, 48, 31))
        self.label_112.setObjectName("label_112")
        self.lineEdit_7_10 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_10.setGeometry(QtCore.QRect(100, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.lineEdit_7_10.setFont(font)
        self.lineEdit_7_10.setText("")
        self.lineEdit_7_10.setObjectName("lineEdit_7_10")
        self.label_113 = QtWidgets.QLabel(self.groupBox_9)
        self.label_113.setGeometry(QtCore.QRect(20, 340, 48, 31))
        self.label_113.setObjectName("label_113")
        self.lineEdit_7_1 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7_1.setGeometry(QtCore.QRect(100, 30, 311, 31))
        self.lineEdit_7_1.setText("")
        self.lineEdit_7_1.setObjectName("lineEdit_7_1")
        self.label_114 = QtWidgets.QLabel(self.groupBox_9)
        self.label_114.setGeometry(QtCore.QRect(20, 28, 48, 31))
        self.label_114.setObjectName("label_114")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(1520, 30, 341, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#3D9140;color:#ffffff")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 40, 91, 31))
        self.pushButton_2.setStyleSheet("background-color:#ff2121;color:#ffffff")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(890, 30, 611, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_12)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 591, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        New_meter_reading.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(New_meter_reading)
        self.statusbar.setObjectName("statusbar")
        New_meter_reading.setStatusBar(self.statusbar)

        self.retranslateUi(New_meter_reading)
        QtCore.QMetaObject.connectSlotsByName(New_meter_reading)

    def retranslateUi(self, New_meter_reading):
        _translate = QtCore.QCoreApplication.translate
        New_meter_reading.setWindowTitle(_translate("New_meter_reading", "新抄表"))
        self.groupBox.setTitle(_translate("New_meter_reading", "单号信息"))
        self.label.setText(_translate("New_meter_reading", "指令单号："))
        self.label_2.setText(_translate("New_meter_reading", "条码区间："))
        self.label_3.setText(_translate("New_meter_reading", "制品名称："))
        self.lineEdit_1.setText(_translate("New_meter_reading", "暂无数据"))
        self.lineEdit_2.setText(_translate("New_meter_reading", "暂无数据"))
        self.lineEdit_3.setText(_translate("New_meter_reading", "暂无数据"))
        self.label_4.setText(_translate("New_meter_reading", "------"))
        self.groupBox_2.setTitle(_translate("New_meter_reading", "抄表结果"))
        self.label_125.setText(_translate("New_meter_reading", "成功:0"))
        self.label_126.setText(_translate("New_meter_reading", "失败:0"))
        self.groupBox_3.setTitle(_translate("New_meter_reading", "一号检测位"))
        self.label_5.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_6.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_7.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_8.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_9.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_10.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_11.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_12.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_13.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_14.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_4.setTitle(_translate("New_meter_reading", "二号检测位"))
        self.label_15.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_16.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_17.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_18.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_19.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_20.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_21.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_22.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_23.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_24.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_5.setTitle(_translate("New_meter_reading", "三号检测位"))
        self.label_25.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_26.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_27.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_28.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_29.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_30.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_31.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_32.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_33.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_34.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_6.setTitle(_translate("New_meter_reading", "四号检测位"))
        self.label_35.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_36.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_37.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_38.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_39.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_40.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_41.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_42.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_43.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_44.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_10.setTitle(_translate("New_meter_reading", "五号检测位"))
        self.label_115.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_116.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_117.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_118.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_119.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_120.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_121.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_122.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_123.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_124.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_7.setTitle(_translate("New_meter_reading", "八号检测位"))
        self.label_85.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_86.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_87.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_88.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_89.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_90.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_91.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_92.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_93.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_94.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_8.setTitle(_translate("New_meter_reading", "六号检测位"))
        self.label_95.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_96.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_97.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_98.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_99.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_100.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_101.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_102.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_103.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_104.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_9.setTitle(_translate("New_meter_reading", "七号检测位"))
        self.label_105.setText(_translate("New_meter_reading", "进入产测模式"))
        self.label_106.setText(_translate("New_meter_reading", "进入抄表模式"))
        self.label_107.setText(_translate("New_meter_reading", "读取/验证SN"))
        self.label_108.setText(_translate("New_meter_reading", "写入国网ID"))
        self.label_109.setText(_translate("New_meter_reading", "写入模块ID"))
        self.label_110.setText(_translate("New_meter_reading", "LED灯检测"))
        self.label_111.setText(_translate("New_meter_reading", "扫码配对信息"))
        self.label_112.setText(_translate("New_meter_reading", "抄表检测"))
        self.label_113.setText(_translate("New_meter_reading", "抄表结果"))
        self.label_114.setText(_translate("New_meter_reading", "获取条码"))
        self.groupBox_11.setTitle(_translate("New_meter_reading", "控制器"))
        self.pushButton.setText(_translate("New_meter_reading", "启动"))
        self.pushButton_2.setText(_translate("New_meter_reading", "停止"))
        self.pushButton_3.setText(_translate("New_meter_reading", "配置文件"))
        self.groupBox_12.setTitle(_translate("New_meter_reading", "运行信息"))
